import { DASHBOARD_PAGES } from './pages-url.config';

export const AccessMap = {
  admin: [
    DASHBOARD_PAGES.DASHBOARD,
    DASHBOARD_PAGES.USERS,
    DASHBOARD_PAGES.PUBLICATIONS,
    DASHBOARD_PAGES.VERIFICATION,
    DASHBOARD_PAGES.REVIEWS,
    DASHBOARD_PAGES.COMPLAINTS,
    DASHBOARD_PAGES.EQUIPMENT_CATEGORIES,
    DASHBOARD_PAGES.BRANDS,
  ],

  moderator: [
    DASHBOARD_PAGES.DASHBOARD,
    DASHBOARD_PAGES.BRANDS,
    DASHBOARD_PAGES.EQUIPMENT_CATEGORIES,
    DASHBOARD_PAGES.PUBLICATIONS,
    DASHBOARD_PAGES.VERIFICATION,
    DASHBOARD_PAGES.REVIEWS,
    DASHBOARD_PAGES.COMPLAINTS,
  ],
} as const;

export type Role = keyof typeof AccessMap;
